export const storageKeys = {
  THEME: "THEME",
  PASSCODE: "CSIPRO_PASSCODE",
  FIREBASE_UID: "CSIPRO_FIREBASE_UID",
  SELECTED_ROOM: "CSIPRO_SELECTED_ROOM",
  SEEN_ONBOARDING: "CSIPRO_SEEN_ONBOARDING",
};
