export const storageKeys = {
  THEME: "THEME",
  PASSCODE: "CSIPRO_PASSCODE",
  FIREBASE_UID: "CSIPRO_FIREBASE_UID",
  SELECTED_ROOM: "CSIPRO_SELECTED_ROOM",
  FIRST_TIME_USER: "CSIPRO_FIRST_TIME_USER",
};
